### ISSUE TITLE
Cannot import module Cartesia!

### ISSUE THREAD

**Issue by OnlinePage** [cartesia-ai/cartesia-js#1]
Hi i tried using this in my node js app, (non es6) this way:
```javascript
const Cartesia = require("@cartesia/cartesia-js");
```
And getting error:
```javascript
Error: Cannot find module 'C:\Users\daddy\...\node_modules\@cartesia\cartesia-js\dist\index.js
```

Although I see the cartesia in my node modules folder installed:
![image](https://github.com/cartesia-ai/cartesia-js/assets/61045650/24a231ed-49fc-41c7-b482-0f567e78ae4c)

I tried re installation but same error!

**Comment by kbrgl** [comment]
Hi @OnlinePage, Node.js is not supported yet (our code is currently bundled for the browser), but adding support is high on our priorities.

**Comment by neops1** [comment]
Same thing in nextjs ! Module not found: Can't resolve '@cartesia/cartesia-js'

**Comment by sauhardjain** [comment]
hey @neops1 we recently released an alpha version of our JavaScript client's v1 release on NPM—could you give that a go and see if it works for you? you can install it with `npm install @cartesia/cartesia-js@alpha`

our package uses the ES6 module system so try importing it as `import Cartesia from "@cartesia/cartesia-js`. if you're using Node, you'll have to add `"type": "module"` to your `package.json`

let us know if you run into any issues at all!
