### ISSUE TITLE
Can't clone voices in Node.js

### ISSUE THREAD

**Issue by soylomass** [cartesia-ai/cartesia-js#12]
Using the clone method in Node.js to clone a voice, using a Blob for the voice clip, results in the following error:

```
[Cartesia] Error cloning voice FetchError: invalid json response body at https://api.cartesia.ai/voices/clone/clip reason: Unexpected token e in JSON at position 0
    at /Users/federico/Projects/miniapps-api/node_modules/node-fetch/lib/index.js:273:32
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at VoiceService.create (/Users/federico/Projects/miniapps-api/src/api/voice/voice.service.ts:212:19)
    at VoiceController.create (/Users/federico/Projects/miniapps-api/src/api/voice/voice.controller.ts:89:12) {
  type: 'invalid-json'
}
```

After debugging, found out that the API was returning an string (the sdk is only coded to support json responses in the clone method):

```
'error parsing clip
'
```

I tried replicating your implementation, but using native Node fetch instead of the package you use (cross-fetch) and it worked, so the problem must be that library messing up with the file somehow.

**Comment by fern-support** [comment]
@soylomass the package is now updated to use node fetch on legacy node versions or the built in fetch. Please let us know if you have any issues on 2.x
