### ISSUE TITLE
CJS build is broken

### ISSUE THREAD

**Issue by noahlt** [cartesia-ai/cartesia-js#14]
This package should dual-build ESM and CJS builds, but the CJS builds are broken. A very thoughtful user created a [repro here].

> To run the repro:
> 
> ```sh
> npm i
> CARTESIA_API_KEY=... node --import tsx index.ts
> ```
> 
> It is a typescript project, run with tsx. Here is what you I with the latest cartesia-js version:
> 
> ```
> dev/cartesia-test - [main] » CARTESIA_API_KEY=... node --import tsx index.ts
> Failed to connect to Cartesia: TypeError: import_emittery2.default is not a constructor
> (node:3146) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
> (Use `node --trace-deprecation ...` to show where the warning was created)
> /Users/posobin/2024/dev/cartesia-test/node_modules/@cartesia/cartesia-js/dist/index.cjs:410
>       throw new Error("Not connected to WebSocket. Call .connect() first.");
>             ^
> 
> Error: Not connected to WebSocket. Call .connect() first.
>     at WebSocket.send (/Users/posobin/2024/dev/cartesia-test/node_modules/@cartesia/cartesia-js/dist/index.cjs:410:13)
>     at app (/Users/posobin/2024/dev/cartesia-test/index.ts:34:36)
> 
> Node.js v23.1.0
> ```
> 
> If I replace lines 
> 
> ```
> var import_emittery2 = __toESM(require("emittery"), 1);
> ...
> var import_emittery = __toESM(require("emittery"), 1);
> ```
>
> in cartesia-js's dist/index.cjs with __toESM(...).default, then it works.

Seems like a problem with our `tsup` configuration.

**Comment by fern-support** [comment]
@noahlt this should be fixed in `2.0.3`! If the user is still seeing issues, please let us know.
