### ISSUE TITLE
Experimental controls is broken - Doesn't work with ts sdk

### ISSUE THREAD

**Issue by benjalimm** [cartesia-ai/cartesia-js#27]
When experimental control is included, I get a 422 error
<img width="1722" alt="image" src="https://github.com/user-attachments/assets/42f58438-00bc-4ab9-a675-728e44f5f988" />

I wonder if it's because emotion is meant to be an array rather than a single property according to the docs,. However, typescript won't let me define it as an array.

<img width="461" alt="image" src="https://github.com/user-attachments/assets/77b8d4a7-4878-470b-acfc-e8a8730417c4" />

<img width="756" alt="image" src="https://github.com/user-attachments/assets/07145cac-fd8d-4a20-9fe8-cbd84cbe5c26" />

**Comment by noahlt** [comment]
Thanks for the report. v2.1.1 now correctly takes in a list of emotions. Here's some example code:

```ts
import { Cartesia, CartesiaClient } from "@cartesia/cartesia-js";

const client = new CartesiaClient({ apiKey: process.env.VITE_CARTESIA_API_KEY });

// ...

  const handleEmotions = async () => {
    const resp = await client.tts.bytes({
      modelId: "sonic-preview",
      transcript: "I am not happy.",
      voice: {
        id: "f785af04-229c-4a7c-b71b-f3194c7f08bb",
        mode: "id",
        experimentalControls: {
          speed: 1,
          emotion: [Cartesia.Emotion.AngerHigh],
        }
      },
      outputFormat: { container: "mp3", bitRate: 128000, sampleRate: 24000 },
    });
  }
```
