### ISSUE TITLE
Provide a sample implementation for input streaming with context over websocket

### ISSUE THREAD

**Issue by xumx** [cartesia-ai/cartesia-js#3]
Please update sample code 
https://github.com/cartesia-ai/cartesia-js?tab=readme-ov-file#tts-over-websocket

with support for 
https://docs.cartesia.ai/api-reference/endpoints/stream-speech-websocket#input-streaming-with-contexts

How should the subsequent "websocket.send" be added to the first stream? 

```js
// Create a stream.
const response = await websocket.send({
	model_id: "sonic-english",
	voice: {
		mode: "embedding",
		embedding: Array(192).fill(1.0),
	},
	transcript: "Hello, world!"
	// The WebSocket sets output_format on your behalf.
});
```

**Comment by sauhardjain** [comment]
@xumx we've published v1.0.1 of the JS client that addresses this. You can check out usage [here](https://github.com/cartesia-ai/cartesia-js?tab=readme-ov-file#input-streaming-with-contexts)
