### ISSUE TITLE
No WebSocket implementation available. You should define options.WebSocket.

### ISSUE THREAD

**Issue by derenrich** [cartesia-ai/cartesia-js#8]
I'm trying to use this API in a node backend

When starting the websocket I get:

`WebSocket implementation available. You should define options.WebSocket.`

`For example, if you're using node.js, run `npm install ws`, and then in your code`

But your implementation doesn't expose any way to pass the polyfill through to the partysocket constructor.

**Comment by kbrgl** [comment]
Closed by #17.
