### ISSUE TITLE
Expose non-websocket TTS

### ISSUE THREAD

**Issue by derenrich** [cartesia-ai/cartesia-js#9]
I see that the API provides a [simple POST endpoint](https://docs.cartesia.ai/reference/api-reference/rest/stream-speech-bytes) that gets me the bytes data of an audio file.

Seems this endpoint is not supported by this library.  This is problematic for me because it seems the websocket API doesn't return an MP3 and so I'm forced to encode the file myself.

**Comment by kbrgl** [comment]
We're going to be adding this shortly!

**Comment by kbrgl** [comment]
This is in. The latest client supports the bytes endpoint. Go to https://docs.cartesia.ai/get-started/make-an-api-request and tab into JavaScript/TypeScript to see an example.
